### ISSUE TITLE
My markbot won't stop loading 

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/flexible-info-card#1]
@thatkidmadrid 

Hey Christian, I been having some problems with markbot It wont load I tried to restart my computer but same thing.
Unfortunately I can go to lab this week to get this checked out because I have work at that time. It started acting up today I think. Im trying to work on the flexible-info-card but the first assignment worked no problem. 
Thanks, if you could let me know what I can do.   
<img width="1680" alt="Screen Shot 2021-09-14 at 4 59 28 PM" src="https://user-images.githubusercontent.com/77282460/133333117-260b2469-e182-4dc7-a9ad-e8d93da74530.png">

**Comment by thatkidmadrid** [comment]
Hey Emma - thanks for bringing this to my attention.

I believe this was happening in the class demo where it would seem to hang but I wasn't able to find a clear solution yet. After closing and re-opening markbot the problem seemed to be resolved, but I'm not sure what the key is especially after restarting your machine.

@thomasjbradley Any ideas what could be going on here?

Anyways, if you are not able to submit through markbot just let me know like you did here, and I will make a note to take a look at your project's gh-pages output when I'm reviewing the grades for the activities.

In this case it would be [https://emmajlussier.github.io/flexible-info-card/](https://emmajlussier.github.io/flexible-info-card/))

**Make sure your latest changes are pushed to your forked repository, and that the gh-pages output is as expected**

**Comment by EmmaJLussier** [comment]
Thank you Christian! 
It has continued to happen today unfortunately I can keep dragging the file in it just won't fully load.Do you mind checking my latest commit to see if I'm on right track? This is what I get when I drag it in, so I don't know if I got it or not.
<img width="1680" alt="Screen Shot 2021-09-15 at 6 57 02 AM" src="https://user-images.githubusercontent.com/77282460/133422049-905f8771-0d34-40d2-9eb1-65a5df89faa9.png">

**Comment by thatkidmadrid** [comment]
Hey Emma,
your gh-pages output looks incomplete on my end, but taking a look at your commits, it looks like you're on the right track.

I see you've been writing clear Commit Messages that describe your progress, but I don't see any styling past a few link styles and adding flex to the section (I do notice there are two `display` properties, so take a look at that - the browser will keep the latest and override any previous properties if they appear multiple times within the same selector)

![Screen Shot 2021-09-15 at 9 13 45 AM](https://user-images.githubusercontent.com/6340290/133439929-56680a36-129b-41f3-b733-48557060c584.png)
![Screen Shot 2021-09-15 at 9 13 59 AM](https://user-images.githubusercontent.com/6340290/133439931-ac036c2c-1867-4953-93fd-edd6d9796f52.png)

Please make sure you check your [gh-pages output](https://emmajlussier.github.io/flexible-info-card/) and compare with the reference in the screenshots folder to confirm your completion

**Comment by thomasjbradley** [comment]
I just downloaded the code & tried in Markbot and it worked okay.
@thatkidmadrid Did you try downloading it and dropping it in your Markbot?

**Comment by thatkidmadrid** [comment]
@thomasjbradley I did try to download, but i noticed that at the step where it is comparing to the reference screenshot it was hanging. Perhaps if the styling is not complete enough and is too different from the reference, it will have trouble with the last step.

@EmmaJLussier Please try your best to get as close to the reference using your browser to preview, then try running through markbot again. After adding a few more styles I was able to get the folder to finish running in markbot.

If that still does not work, make sure your gh-pages output is as complete as you think it should be and I will grade your activity through gh-pages manually

**Comment by EmmaJLussier** [comment]
Thank you! markbot is working now, I happened to get this far. I just become stuck on how to get the content spaced out properly. 
<img width="1680" alt="Screen Shot 2021-09-16 at 7 12 46 AM" src="https://user-images.githubusercontent.com/77282460/133602426-8c4754b2-7db9-4605-bad2-fd7269f87fc4.png">
![Screen Shot 2021-09-16 at 7 12 46 AM (2)](https://user-images.githubusercontent.com/77282460/133602433-51fd95db-b3d5-4a7f-86a5-a4c6bc9382b4.png)

**Comment by EmmaJLussier** [comment]
Thank you @thatkidmadrid @thomasjbradley  for your help! Markbot is working again and I got in the assignment.
